/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PostsImport } from './routes/Posts'
import { Route as AddPostsImport } from './routes/AddPosts'
import { Route as AboutImport } from './routes/About'
import { Route as PostsPostIdImport } from './routes/posts.$postId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const PostsRoute = PostsImport.update({
  path: '/Posts',
  getParentRoute: () => rootRoute,
} as any)

const AddPostsRoute = AddPostsImport.update({
  path: '/AddPosts',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/About',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const PostsPostIdRoute = PostsPostIdImport.update({
  path: '/posts/$postId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/About': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/AddPosts': {
      preLoaderRoute: typeof AddPostsImport
      parentRoute: typeof rootRoute
    }
    '/Posts': {
      preLoaderRoute: typeof PostsImport
      parentRoute: typeof rootRoute
    }
    '/posts/$postId': {
      preLoaderRoute: typeof PostsPostIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutRoute,
  AddPostsRoute,
  PostsRoute,
  PostsPostIdRoute,
])

/* prettier-ignore-end */
